---
# file: project/docker-server.yml

- hosts: docker-server
  become: false
  gather_facts: true
  pre_tasks:

    - set_fact: fact_role_name="{{ lookup('env','ANSIBLE_ROLE_NAME') }}"
    - debug: var=fact_role_name

    - set_fact: fact_role_path="{{ lookup('pipe','pwd') }}/roles/docker-server"
    - debug: var=fact_role_path

  roles:

    - docker-server
